config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :urls, only: [ :create, :show, :destroy, :new ] do
    resources :visits, only: :index
    member do
      get "preview"
    end
  end

  get "/:short" => "urls#redirect", as: :redirect_url, constraints: { short: /t[A-Za-z0-9]{0,5}/ }
  get "/visits/search", to: "visits#search", as: :visits_search
  get "/visits/analytics", to: "visits#analytics"
  get "/urls/:url_id/visits/download", to: "visits#download", as: :url_visits_download

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "urls#new"
end

app/models/url.rb
class Url < ApplicationRecord
  after_create :shortened

  default_scope { order(created_at: :desc) }

  belongs_to :user, optional: true
  has_many :visits, dependent: :destroy

  validates :target, presence: true
  validates :title, presence: true

  def shortened
    self.update(short: "t" + to_base62(self.id))
  end

  def to_base62(num)
    quotient = num
    base62 = ""
    while quotient > 0
      remainder = quotient % 62
      quotient = quotient / 62
      base62.prepend(base62_map(remainder))
    end
    base62
  end
  def base62_map(key)
    {
      0 => "0",
      1 => "1",
      2 => "2",
      3 => "3",
      4 => "4",
      5 => "5",
      6 => "6",
      7 => "7",
      8 => "8",
      9 => "9",
      10 => "A",
      11 => "B",
      12 => "C",
      13 => "D",
      14 => "E",
      15 => "F",
      16 => "G",
      17 => "H",
      18 => "I",
      19 => "J",
      20 => "K",
      21 => "L",
      22 => "M",
      23 => "N",
      24 => "O",
      25 => "P",
      26 => "Q",
      27 => "R",
      28 => "S",
      29 => "T",
      30 => "U",
      31 => "V",
      32 => "W",
      33 => "X",
      34 => "Y",
      35 => "Z",
      36 => "a",
      37 => "b",
      38 => "c",
      39 => "d",
      40 => "e",
      41 => "f",
      42 => "g",
      43 => "h",
      44 => "i",
      45 => "j",
      46 => "k",
      47 => "l",
      48 => "m",
      49 => "n",
      50 => "o",
      51 => "p",
      52 => "q",
      53 => "r",
      54 => "s",
      55 => "t",
      56 => "u",
      57 => "v",
      58 => "w",
      59 => "x",
      60 => "y",
      61 => "z"
    }[key]
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end
  def create
    target = params[:url][:target]
    begin
      response = fetch(target)
      title = Nokogiri::HTML(response.body).title
      title = "Title tag not available" if title.nil?

      @url = Url.new(target: target, title: title)

      if verify_recaptcha(model: @url) && @url.save
        if current_user
          current_user.urls << @url
        end

        redirect_to preview_url_path(@url)
      else
        flash[:alert] = "Shortening process failed"
        redirect_to root_path
      end
    rescue Exception => e
      flash[:alert] = "#{e}"
      redirect_back_or_to root_path
    end
  end

  def preview
    @new_url = Url.new
    @url = Url.find(params[:id])
  end
  def redirect
    request_time = Time.new
    ip = request.remote_ip
    location = get_location(ip)

    @url = Url.find_by(short: params[:short])
    @url.visits.create(ip: ip, request_time: request_time, city: location[:city], country: location[:country])
    redirect_to(@url.target, allow_other_host: true)
  end

  def destroy
    @url = Url.find(params[:id])

    # only tracked urls can be destroyed
    if current_user.nil? || current_user.id != @url.user_id
      redirect_back_or_to root_path
    end

    @url.destroy
    redirect_to user_path(current_user)
  end

  private

  def fetch(target, limit = 10)
    raise ArgumentError, "too many HTTP redirects" if limit == 0

    response = Net::HTTP.get_response(URI.parse(target))

    case response
    when Net::HTTPSuccess then
      response
    when Net::HTTPRedirection then
      location = response["location"]
      fetch(location, limit - 1)
    else
      response.value
    end
  end

  def get_location(ip)
    geo_url = "https://api-bdc.net/data/ip-geolocation?ip=#{ip}&localityLanguage=en&key=#{Rails.application.credentials.bdc_api_key}"
    p geo_url

    begin
      response =  JSON.parse(fetch(geo_url).body)
    rescue Exception => e
      puts e
      return {
        city: "NA",
        country: "NA"
      }
    end

    location = {}

    if response["location"].nil?
      location[:city] = "NA"
    else
      location[:city] = response["location"]["city"]
    end

    if response["country"].nil?
      location[:country] = "NA"
    else
      location[:country] = response["country"]["name"]
    end

    location
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/new.html.erb
<div class="flex flex-col justify-center items-center min-h-[95%] text-xl gap-2" data-controller="notice">
  <%= render 'partials/navbar' %>
  <%= render "partials/forms/url", url: @url %>
  <%= render 'partials/alert' %>
  <div class="flex gap-5 text-base md:text-xl">
    <% if current_user %>
      <%= link_to "your links", user_path(current_user), class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% end %>
    <%= link_to "analytics", visits_search_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% if current_user %>
      <%= button_to "log out", destroy_user_session_path, method: :delete, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% else %>
      <%= link_to "log in", new_user_session_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium", data: { action: "mouseover->notice#reveal" } %>
      <%= link_to "sign up", new_user_registration_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium", data: { action: "mouseover->notice#reveal" } %>
    <% end %>
  </div>

  <% unless current_user %>
    <p class="text-darkslategrey font-medium my-5" data-notice-target="reason">sign up to track your links!</p>
  <% end %>
</div>

app/views/urls/preview.html.erb
<div class="flex flex-col justify-center items-center min-h-[92%] text-xl gap-3" data-controller="notice">
  <%= render 'partials/navbar' %>
  <%= render "partials/forms/url", url: @new_url %>
  <%= render "partials/alert" %>
  <div class="flex gap-4 justify-between items-center text-base md:text-xl" data-controller="clipboard">
    <div class="flex-1 text-cream">
      <span data-clipboard-target="notice">shortened link: </span>
      <a href="<%= redirect_url_path(@url.short) %>" target="_blank" class="text-vanilla font-medium hover:underline" data-clipboard-target="url">snippit.my/<%= @url.short %></a>
    </div>
    <div data-action="click->clipboard#copy">
      <svg class="w-4 md:w-5 text-cream fill-current hover:text-vanilla cursor-pointer" viewBox="0 0 24 24"><path d="M19 21H8V7h11m0-2H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2m-3-4H4a2 2 0 0 0-2 2v14h2V3h12V1Z"  /></svg>
    </div>
  </div>
  <div class="flex gap-4 justify-between items-center text-base md:text-xl" data-controller="clipboard">
    <div class="flex-1 text-cream">
      <span data-clipboard-target="notice">link analytics: </span>
      <a href="<%= url_visits_path(@url) %>" target="_blank" class="text-vanilla font-medium hover:underline" data-clipboard-target="url">snippit.my<%= url_visits_path(@url) %></a>
    </div>
    <div data-action="click->clipboard#copy">
      <svg class="w-4 md:w-5 text-cream fill-current hover:text-vanilla cursor-pointer" viewBox="0 0 24 24"><path d="M19 21H8V7h11m0-2H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2m-3-4H4a2 2 0 0 0-2 2v14h2V3h12V1Z"  /></svg>
    </div>
  </div>

  <div class="flex gap-5 text-base md:text-xl">
    <% if current_user %>
      <%= link_to "your links", user_path(current_user), class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% end %>
    <%= link_to "analytics", visits_search_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% if current_user %>
      <%= button_to "log out", destroy_user_session_path, method: :delete, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% else %>
      <%= link_to "log in", new_user_session_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium", data: { action: "mouseover->notice#reveal" } %>
      <%= link_to "sign up", new_user_registration_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium", data: { action: "mouseover->notice#reveal" } %>
    <% end %>
  </div>
</div>

app/views/urls/show.html.erb
<div class="flex justify-center p-4">
  <div class="flex justify-between items-center w-full md:w-[768px]">
    <h1 class="text-4xl font-bold text-vanilla hover:underline"><%= link_to "snippit", home_path %></h1>
    <div class="flex gap-4">
      <% if current_user %>
        <%= link_to "your links", user_path(current_user), class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
      <% end %>
      <%= link_to "shortener", home_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
      <%= link_to "search", search_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
      <% if current_user %>
        <%= button_to "log out", destroy_user_session_path, method: :delete, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
      <% else%>
        <%= link_to "log in", new_user_session_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
      <% end %>
    </div>
  </div>
</div>


<div class="m-4 md:mx-auto p-4 md:w-[768px] text-cream rounded-md border border-cream shadow-md shadow-grey-200">
  <h5 class="truncate font-medium text-cream"><%= @url.title %></h5>
  <div>short link: <a href="<%= redirect_url_path(@url.short) %>" target="_blank" class="font-medium text-vanilla hover:underline">snippit.my/<%= @url.short %></a></div>
  <div class="truncate">original link: <a href="<%= @url.target %>" target="_blank" class="font-medium text-vanilla hover:underline"><%= @url.target %></a></div>
</div>

<h1 class="text-3xl font-medium m-4 md:w-[768px] md:mx-auto text-vanilla"><%= pluralize(@visits_count, "visit") %></h1>


<% unless @visits.empty? %>
  <div class="grid grid-rows-<%= @visits.length - 1 %> text-sm md:w-[768px]  md:mx-auto rounded-md border border-vanilla shadow-md shadow-grey-200 p-3">
    <div class="grid grid-cols-8 text-sm md:w-[768px] md:mx-auto rounded-md">
      <div class="p-2 py-3 col-span-2 font-bold rounded-md text-vanilla">ip address</div>
      <div class="p-2 py-3 font-bold col-span-2 rounded-md text-vanilla">city</div>
      <div class="p-2 py-3 font-bold col-span-2 rounded-md text-vanilla">country</div>
      <div class="p-2 py-3 font-bold col-span-2 rounded-md text-vanilla">datetime</div>
    </div>
    <% @visits.each_with_index do |visit, index| %>
      <div class="grid grid-cols-8 text-sm rounded text-cream">
        <div class="p-2 py-3 col-span-2 truncate"><%= visit.ip %></div>
        <div class="p-2 py-3 col-span-2 truncate"><%= visit.city %></div>
        <div class="p-2 py-3 col-span-2 truncate"><%= visit.country %></div>
        <div class="p-2 py-3 col-span-2 "><%= local_time(Time.new(visit.request_time), "%d/%m/%y %-l:%M%P") %></div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @pagy.count > @pagy.limit %>
  <div class="flex flex-col items-center gap-4 fixed bottom-10 w-full">
    <%== pagy_info(@pagy, item_name: "visit".pluralize(@pagy.count)).downcase.sub("in total", "most recent visits") %>
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>