config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :urls, only: [ :create, :show, :destroy, :new ] do
    resources :visits, only: :index
    member do
      get "preview"
    end
  end

  get "/:short" => "urls#redirect", as: :redirect_url, constraints: { short: /t[A-Za-z0-9]{0,5}/ }
  get "/visits/search", to: "visits#search", as: :visits_search
  get "/visits/analytics", to: "visits#analytics"
  get "/urls/:url_id/visits/download", to: "visits#download", as: :url_visits_download

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "urls#new"
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :url, counter_cache: true

  default_scope { order(created_at: :desc) }
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  require "csv"
  def index
    @url = Url.find(params[:url_id])

    # if url was created with a user, the report only available to the user
    if @url.user_id
      if current_user.nil? || current_user.id != @url.user_id
        flash[:alert] = "Unauthorized access! The analytics page is only available to the user that created the short link."
        redirect_to root_path
      end
    end

    @visits_count = @url.visits.count
    @visits = @url.visits.limit(200)
    @pagy, @visits = pagy(@visits, limit: 12)
  end

  def download
    @url = Url.find(params[:url_id])

    # if url was created with a user, the report only available to the user
    if @url.user_id
      if current_user.nil? || current_user.id != @url.user_id
        flash[:alert] = "Unauthorized access! Downloading analytics report is only available to the user that created the short link."
        redirect_to root_path
      end
    end

    @visits = @url.visits

    begin
      compressed_filestream = Zip::OutputStream.write_buffer(::StringIO.new("")) do |zip|
        zip.put_next_entry "#{@url.short}-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"
        zip.print to_csv(@visits)
      end
      compressed_filestream.rewind
      send_data compressed_filestream.read, filename: "#{@url.short}-#{DateTime.now.strftime("%d%m%Y%H%M")}.zip"
    rescue Exception => e
      flash[:alert] = "#{e}"
      redirect_to url_visits_path(@url)
    end
  end

  def analytics
    @short = params[:url].split("/")[-1]
    @url = Url.find_by(short: @short)

    if @url.nil?
      flash[:alert] = "No such links found"
      redirect_to visits_search_path
    else
      redirect_to url_visits_path(@url)
    end
  end

  def search
  end

  private

  def to_csv(visits)
    column_names = visits[0].attributes.keys
    CSV.generate do |csv|
      csv << column_names
      visits.each do |visit|
        csv << visit.attributes.values_at(*column_names)
      end
    end
  end
end

app/helpers/visit_helper.rb
module VisitHelper
end

app/views/visits/index.html.erb
<div class="flex flex-col bg-darkslategrey min-h-screen">
  <div class="flex justify-center p-4">
    <div class="flex justify-between items-center w-full md:w-[768px]">
      <h1 class="text-lg md:text-4xl font-bold text-vanilla hover:underline"><%= link_to "snippit", root_path %></h1>
      <div class="flex text-xs md:text-base gap-2 md:gap-4">
        <% if current_user %>
          <%= link_to "your links", user_path(current_user), class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <% end %>
        <%= link_to "shortener", root_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <%= link_to "search", visits_search_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <% if current_user %>
          <%= button_to "log out", destroy_user_session_path, method: :delete, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <% else%>
          <%= link_to "log in", new_user_session_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <% end %>
      </div>
    </div>
  </div>

  <% if flash[:alert] %>
    <div class="bg-hunyadi py-2 px-3 md:w-[768px] rounded-lg text-sm text-auburn font-bold alert mx-auto" data-controller="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="m-4 text-xs md:text-base md:mx-auto p-4 md:w-[768px] text-cream rounded-md border border-cream shadow-md shadow-grey-200">
    <h5 class="truncate font-medium text-cream"><%= @url.title %></h5>
    <div>short link: <a href="<%= redirect_url_path(@url.short) %>" target="_blank" class="font-medium text-vanilla hover:underline">snippit.my/<%= @url.short %></a></div>
    <div class="truncate">original link: <a href="<%= @url.target %>" target="_blank" class="font-medium text-vanilla hover:underline"><%= @url.target %></a></div>
  </div>

  <div class="flex items-center m-4 md:w-[768px] md:mx-auto gap-3">
    <h1 class="text-lg md:text-3xl font-medium text-vanilla"><%= pluralize(@visits_count, "visits") %></h1>
    <% unless @visits_count.zero? %>
      <%= link_to url_visits_download_path, target: "_blank" do %>
        <svg class="w-4 md:w-6 md:mt-[2px] text-vanilla fill-current hover:text-cream cursor-pointer" viewBox="0 0 24 24"><title>download csv file</title><path d="M14,2H6C4.89,2 4,2.89 4,4V20C4,21.11 4.89,22 6,22H18C19.11,22 20,21.11 20,20V8L14,2M12,19L8,15H10.5V12H13.5V15H16L12,19M13,9V3.5L18.5,9H13Z" /></svg>
      <% end %>
    <% end %>
  </div>

  <% unless @visits.empty? %>
    <div class="grid grid-rows-<%= @visits.length - 1 %> text-xs md:text-sm md:w-[768px]  md:mx-auto rounded-md border border-vanilla shadow-md shadow-grey-200 p-3 m-2">
      <div class="grid grid-cols-8 md:w-[768px] md:mx-auto rounded-md">
        <div class="p-2 py-3 col-span-2 font-bold rounded-md text-vanilla">ip address</div>
        <div class="p-2 py-3 font-bold col-span-2 rounded-md text-vanilla">city</div>
        <div class="p-2 py-3 font-bold col-span-2 rounded-md text-vanilla">country</div>
        <div class="p-2 py-3 font-bold col-span-2 rounded-md text-vanilla">datetime</div>
      </div>
      <% @visits.each_with_index do |visit, index| %>
        <div class="grid grid-cols-8 rounded text-cream">
          <div class="p-2 py-3 col-span-2 truncate"><%= visit.ip %></div>
          <div class="p-2 py-3 col-span-2 truncate"><%= visit.city %></div>
          <div class="p-2 py-3 col-span-2 truncate"><%= visit.country %></div>
          <div class="p-2 py-3 col-span-2 "><%= local_time(Time.new(visit.request_time), "%d/%m/%y %-l:%M%P") %></div>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @pagy.count > @pagy.limit %>
    <div class="flex flex-col items-center gap-4 w-full p-3">
      <%== pagy_info(@pagy, item_name: "visits".pluralize(@pagy.count)).downcase.sub("in total", "most recent visits") %>
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/visits/search.html.erb
<div class="flex flex-col justify-center items-center min-h-[95%] text-xl gap-2" data-controller="notice">
  <%= render 'partials/navbar' %>
  <%= form_with url: "/visits/analytics", method: :get, class: "flex flex-col md:flex-row w-full gap-2 justify-center py-2 px-6 md:w-[768px]" do |form| %>
    <%= form.url_field :url, required: true, class: "flex-1 bg-gray-100 rounded-lg border-transparent focus:border-transparent focus:ring-0 autofill:bg-transparent", placeholder: "https://snippit.my/t______" %>
    <%= form.submit value: "get analytics", class: "p-2 rounded-lg cursor-pointer font-medium text-base bg-darkslategrey text-vanilla border border-vanilla transition hover:bg-vanilla hover:text-darkslategrey" %>
  <% end %>
  <%= render 'partials/alert'%>
  <div class="flex gap-5 text-base md:text-xl">
    <% if current_user %>
      <%= link_to "your links", user_path(current_user), class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% end %>
    <%= link_to "shortener", root_path, class: "text-cream hover:text-vanilla cursor-pointer hover:underline font-medium" %>
    <% if current_user %>
      <%= button_to "log out", destroy_user_session_path, method: :delete, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
    <% else %>
      <%= link_to "log in", new_user_session_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium", data: { action: "mouseover->notice#reveal" } %>
      <%= link_to "sign up", new_user_registration_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium", data: { action: "mouseover->notice#reveal" } %>
    <% end %>
  </div>
  <% unless current_user %>
    <p class="text-darkslategrey font-medium my-5" data-notice-target="reason">sign up to track your links!</p>
  <% end %>
</div>