config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :urls, only: [ :create, :show, :destroy, :new ] do
    resources :visits, only: :index
    member do
      get "preview"
    end
  end

  get "/:short" => "urls#redirect", as: :redirect_url, constraints: { short: /t[A-Za-z0-9]{0,5}/ }
  get "/visits/search", to: "visits#search", as: :visits_search
  get "/visits/analytics", to: "visits#analytics"
  get "/urls/:url_id/visits/download", to: "visits#download", as: :url_visits_download

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "urls#new"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :urls
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :show ]
  def show
    @user = User.find(params[:id])

    if @user != current_user
      flash[:alert] = "Unauthorized access! Log in to view your links"
      redirect_back_or_to root_path
    end

    @urls = @user.urls
    @pagy, @urls = pagy(@urls, limit: 8)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="flex flex-col bg-darkslategrey min-h-screen" >

  <div class="flex justify-center p-4 ">
    <div class="flex justify-between items-center w-full md:w-[768px]">
      <h1 class="text-lg md:text-4xl font-bold text-vanilla hover:underline"><%= link_to "snippit", root_path %></h1>
      <div class="flex gap-4 text-xs md:text-base">
        <%= link_to "shortener", root_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <%= link_to "search", visits_search_path, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <% if current_user %>
          <%= button_to "log out", destroy_user_session_path, method: :delete, class: "text-cream cursor-pointer hover:underline hover:text-vanilla font-medium" %>
        <% end %>
      </div>
    </div>
  </div>

  <h1 class="text-lg md:text-3xl font-medium m-4 md:w-[768px] md:mx-auto text-vanilla"><%= pluralize(@pagy.count, "url") %></h1>

  <% @urls.each do |url| %>
    <div class="my-1 mx-2  md:my-2 md:mx-auto p-4 md:w-[768px] text-xs md:text-base rounded-md text-cream  border border-cream shadow-md shadow-grey-200" data-controller="urlclipboard">
      <h5 class="truncate font-medium text-cream hover:underline" ><%= link_to "#{url.title}", url.target, target: "_blank" %></h5>
      <div class="flex justify-between">
        <div class="flex items-center gap-2" >
          <a href="<%= redirect_url_path(url.short) %>" target="_blank" class="font-medium text-vanilla hover:underline" data-urlclipboard-target="link">snippit.my/<%= url.short %></a>
          <div data-action="click->urlclipboard#copy">
            <svg class="w-4 mb-[1.5px] text-cream fill-current hover:text-vanilla cursor-pointer" viewBox="0 0 24 24"><title>copy link</title><path d="M19 21H8V7h11m0-2H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2m-3-4H4a2 2 0 0 0-2 2v14h2V3h12V1Z"/></svg>
          </div>
          <%= link_to url_visits_path(url), target: "_blank" do %>
            <svg class="w-4 mb-[1.5px] text-cream fill-current hover:text-vanilla cursor-pointer" viewBox="0 0 24 24"><title>analytics</title><path d="M3,22V8H7V22H3M10,22V2H14V22H10M17,22V14H21V22H17Z" /></svg>
          <% end %>
        </div>
        <div>
          <%= link_to url_path(url), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this url?"} do %>
            <svg class="w-4 mb-[1.5px] text-cream fill-current hover:text-vanilla cursor-pointer" viewBox="0 0 24 24"><title>delete url</title><path d="M9,3V4H4V6H5V19A2,2 0 0,0 7,21H17A2,2 0 0,0 19,19V6H20V4H15V3H9M7,6H17V19H7V6M9,8V17H11V8H9M13,8V17H15V8H13Z" /></svg>
          <% end %>
        </div>
      </div>
      <div class="hidden" data-urlclipboard-target="notify">
        link copied!
      </div>
    </div>
  <% end %>

  <% if @pagy.count > @pagy.limit %>
    <div class="flex flex-col items-center gap-4 w-full p-3">
      <%== pagy_info(@pagy, item_name: "urls".pluralize(@pagy.count)).downcase %>
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>